## Name : Riddhick Dalal
## Reg No : 24-27-14
## Course : MTech Data Science

In [99]:
import numpy as np

### Question 1:

In [100]:
var1=np.arange(0,30+1,1)
print(var1)
print(var1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
(31,)


In [101]:
var2=var1[:-1].reshape(3,10)
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [102]:
var3=var1[:-1].reshape(3,5,2)
var3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [103]:
var2[1,0]=-1
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-1, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [104]:
print(var1)
print(var3)

[ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[-1 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [105]:
sum_over_second=np.sum(var3,axis=1)
print(sum_over_second)

[[ 20  25]
 [ 59  75]
 [120 125]]


In [106]:
sum_over_third=np.sum(var3,axis=2)
print(sum_over_third)

[[ 1  5  9 13 17]
 [10 25 29 33 37]
 [41 45 49 53 57]]


In [107]:
sum_over_first_second=np.sum(var3,axis=(0,2))
print(sum_over_first_second)

[ 52  75  87  99 111]


In [108]:
print(var2[1:2])
print(var2[0:,-1])
print(var2[:2,-2:])

[[-1 11 12 13 14 15 16 17 18 19]]
[ 9 19 29]
[[ 8  9]
 [18 19]]


#### Question 2 :


In [109]:
arr=np.arange(0,10,1)
arr_broadcasted=arr+1
print(arr_broadcasted)

[ 1  2  3  4  5  6  7  8  9 10]


In [110]:
A=arr+arr.reshape(10,1)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [111]:
data=np.exp(np.random.randn(2,5))


In [112]:
print(data)

[[1.60000635 1.50898441 0.60931832 6.51883295 0.8343094 ]
 [4.14147312 1.1092325  0.45893072 1.00041474 0.92172425]]


In [113]:
means=np.mean(data,axis=0)
sd=np.std(data,axis=0)

In [114]:
print(means)
print(sd)

[2.87073974 1.30910845 0.53412452 3.75962384 0.87801683]
[1.27073338 0.19987595 0.0751938  2.75920911 0.04370743]


In [115]:
std_data=(data-means)/sd

In [116]:
new_means=np.mean(std_data,axis=0)
new_sd=np.std(std_data,axis=0)
print(new_means)
print(new_sd)

[ 0.00000000e+00 -6.10622664e-16 -3.88578059e-16  1.11022302e-16
  0.00000000e+00]
[1. 1. 1. 1. 1.]


### Question 3 :

In [117]:
def vandermonde(N):
    vec=np.arange(N)+1
    vander=vec.reshape(N,1)
    vander=vander**np.arange(N)
    return vander
vander=vandermonde(12)
print(vander)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [118]:
x=np.ones(12)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
b=np.dot(vander,x)
b

array([1.20000000e+01, 4.09500000e+03, 2.65720000e+05, 5.59240500e+06,
       6.10351560e+07, 4.35356467e+08, 2.30688120e+09, 1.22713351e+09,
       9.43953692e+08, 3.73692871e+09, 3.10225064e+08, 3.10073456e+09])

In [120]:
inv_v=np.linalg.inv(vander)
res=np.dot(inv_v,b)
print(res)

[0.99559784 1.00491714 0.99946976 1.00000954 1.         0.99999917
 1.00000018 0.99999999 1.         1.         1.         1.        ]


#### The expected result was a vector having 12 ones, but in actual result some of the values are not exactly 1.

In [121]:
res2=np.linalg.solve(vander,b)
print(res2)


[1.0000114  0.99997033 1.00002961 0.99998507 1.00000423 0.9999993
 1.00000007 1.         1.         1.         1.         1.        ]


#### The result is more closer to the actual result.

### Github Link : <a href="https://github.com/Riddhick/Riddhick_Dalal_24-27-14">Github</a>

#### [https://github.com/Riddhick/Riddhick_Dalal_24-27-14]