### Name : Riddhick Dalal
### Reg No : 24-27-14
### Course : MTech Data Science
### Assignment 2

In [24]:
import numpy as np

### Question 1:

In [25]:
var1=np.arange(0,30+1,1)
print(var1)
print("Shape :"+str(var1.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape :(31,)


In [26]:
var2=var1[:-1].reshape(3,10)
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
var3=var1[:-1].reshape(3,5,2)
var3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [28]:
var2[1,0]=-1
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-1, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [29]:
print(var1)
print(var3)

[ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[-1 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [30]:
sum_over_second=np.sum(var3,axis=1)
print(sum_over_second)

[[ 20  25]
 [ 59  75]
 [120 125]]


In [31]:
sum_over_third=np.sum(var3,axis=2)
print(sum_over_third)

[[ 1  5  9 13 17]
 [10 25 29 33 37]
 [41 45 49 53 57]]


In [32]:
sum_over_first_second=np.sum(var3,axis=(0,2))
print(sum_over_first_second)

[ 52  75  87  99 111]


In [33]:
print(var2[1:2])
print(var2[0:,-1])
print(var2[:2,-2:])

[[-1 11 12 13 14 15 16 17 18 19]]
[ 9 19 29]
[[ 8  9]
 [18 19]]


#### Question 2 :


In [34]:
arr=np.arange(0,10,1)
arr_broadcasted=arr+1
print(arr_broadcasted)

[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
A=arr+arr.reshape(10,1)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [36]:
data=np.exp(np.random.randn(50,5))


In [37]:
print(data)

[[ 0.61019846  3.23139237  0.58090901  1.56423054  0.29927975]
 [ 0.49811301  1.43213469  0.97653187  1.71318824  3.86935499]
 [ 0.87231358  1.1875858   0.55603407  0.53337848  0.62761463]
 [ 5.81223699  2.33986633  2.34615653  0.29267243  0.64998555]
 [ 1.53645126  1.80185833  0.11420313  4.10572037  4.02376905]
 [ 2.48990951  0.95632848  1.39867059  1.88524905  0.80486517]
 [ 2.1992206   0.51388829  2.3009016   1.03971262  1.04711513]
 [ 0.27447619  2.37579179  1.15611915  2.68185641  1.7485073 ]
 [ 1.10841375  0.16509742  4.90719846  2.19178971  1.06548668]
 [ 0.86697955  0.64946806  2.35862373  0.70987438  0.35507968]
 [ 4.54207079  0.81404783  0.45406998  0.87451759  0.61730598]
 [ 0.58614604  0.85559284  1.06224587  4.41333267  0.64270765]
 [ 0.38848404  0.68609457  0.59476708  0.7955648   1.5463431 ]
 [ 0.5607942   1.70476583  0.44005426  1.48268684  0.96173304]
 [ 0.45443679  0.84116659  0.45764365  1.57996362  0.89154922]
 [ 1.70193072  3.83951545  5.2380453   0.73797132  0.33

In [38]:
means=np.mean(data,axis=0)
sd=np.std(data,axis=0)

In [39]:
print('Mean= '+str(means))
print('Standard Diviation= '+str(sd))

Mean= [1.45319495 1.33020872 1.40706929 1.61186806 1.4510479 ]
Standard Diviation= [1.43883113 1.43588783 1.64128835 1.80472582 1.77015123]


In [40]:
std_data=(data-means)/sd

In [41]:
new_means=np.mean(std_data,axis=0)
new_sd=np.std(std_data,axis=0)
print(new_means)
print(new_sd)

[ 2.04281037e-16 -5.24580379e-16 -8.77076189e-17  3.10862447e-17
 -7.99360578e-17]
[1. 1. 1. 1. 1.]


### Question 3 :

In [42]:
def vandermonde(N):
    vec=np.arange(N)+1
    vander=vec.reshape(N,1)
    vander=vander**np.arange(N)
    return vander
vander=vandermonde(12)
print(vander)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [43]:
x=np.ones(12)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
b=np.dot(vander,x)
b

array([1.20000000e+01, 4.09500000e+03, 2.65720000e+05, 5.59240500e+06,
       6.10351560e+07, 4.35356467e+08, 2.30688120e+09, 1.22713351e+09,
       9.43953692e+08, 3.73692871e+09, 3.10225064e+08, 3.10073456e+09])

In [45]:
inv_v=np.linalg.inv(vander)
res=np.dot(inv_v,b)
print(res)

[0.99559784 1.00491714 0.99946976 1.00000954 1.         0.99999917
 1.00000018 0.99999999 1.         1.         1.         1.        ]


#### The expected result was a vector having 12 ones, but in actual result some of the values are not exactly 1.

In [46]:
res2=np.linalg.solve(vander,b)
print(res2)


[1.0000114  0.99997033 1.00002961 0.99998507 1.00000423 0.9999993
 1.00000007 1.         1.         1.         1.         1.        ]


#### The result is more closer to the actual result.

### Github Link : <a href="https://github.com/Riddhick/Riddhick_Dalal_24-27-14">Github</a>

#### [https://github.com/Riddhick/Riddhick_Dalal_24-27-14]