In [19]:
import numpy as np

In [20]:
var1=np.arange(0,30+1,1)
print(var1)
print(var1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
(31,)


In [21]:
var2=var1[:-1].reshape(3,10)
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
var3=var1[:-1].reshape(3,5,2)
var3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [23]:
var2[1,0]=-1
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-1, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [24]:
print(var1)
print(var3)

[ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[-1 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [25]:
sum_over_second=np.sum(var3,axis=1)
print(sum_over_second)

[[ 20  25]
 [ 59  75]
 [120 125]]


In [26]:
sum_over_third=np.sum(var3,axis=2)
print(sum_over_third)

[[ 1  5  9 13 17]
 [10 25 29 33 37]
 [41 45 49 53 57]]


In [27]:
sum_over_first_second=np.sum(var3,axis=(0,2))
print(sum_over_first_second)

[ 52  75  87  99 111]


In [28]:
print(var2[1:2])
print(var2[0:,-1])
print(var2[:2,-2:])

[[-1 11 12 13 14 15 16 17 18 19]]
[ 9 19 29]
[[ 8  9]
 [18 19]]


In [29]:
arr=np.arange(0,10,1)
arr_broadcasted=arr+1
print(arr_broadcasted)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
A=arr+arr.reshape(10,1)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [31]:
data=np.exp(np.random.randn(2,5))


In [32]:
print(data)

[[0.62828771 2.87741072 0.47109762 0.27071401 2.96953038]
 [1.93119524 0.92399104 1.14296293 1.47382809 1.66748912]]


In [33]:
means=np.mean(data,axis=0)
sd=np.std(data,axis=0)

In [34]:
print(means)
print(sd)

[1.27974147 1.90070088 0.80703028 0.87227105 2.31850975]
[0.65145377 0.97670984 0.33593266 0.60155704 0.65102063]


In [35]:
std_data=(data-means)/sd

In [36]:
new_means=np.mean(std_data,axis=0)
new_sd=np.std(std_data,axis=0)
print(new_means)
print(new_sd)

[ 0.00000000e+00  1.11022302e-16  0.00000000e+00  1.11022302e-16
 -2.22044605e-16]
[1. 1. 1. 1. 1.]


In [40]:
def vandermonde(N):
    vec=np.arange(N)+1
    vander=vec.reshape(N,1)
    vander=vander**np.arange(N)
    return vander
vander=vandermonde(12)
print(vander)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57