In [37]:
import numpy as np

In [38]:
var1=np.arange(0,30+1,1)
print(var1)
print(var1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
(31,)


In [39]:
var2=var1[:-1].reshape(3,10)
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [40]:
var3=var1[:-1].reshape(3,5,2)
var3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [41]:
var2[1,0]=-1
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-1, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
print(var1)
print(var3)

[ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[-1 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [43]:
sum_over_second=np.sum(var3,axis=1)
print(sum_over_second)

[[ 20  25]
 [ 59  75]
 [120 125]]


In [44]:
sum_over_third=np.sum(var3,axis=2)
print(sum_over_third)

[[ 1  5  9 13 17]
 [10 25 29 33 37]
 [41 45 49 53 57]]


In [45]:
sum_over_first_second=np.sum(var3,axis=(0,2))
print(sum_over_first_second)

[ 52  75  87  99 111]


In [47]:
print(var2[1:2])
print(var2[0:,-1])
print(var2[:2,-2:])

[[-1 11 12 13 14 15 16 17 18 19]]
[ 9 19 29]
[[ 8  9]
 [18 19]]


In [51]:
arr=np.arange(0,10,1)
arr_broadcasted=arr+1
print(arr_broadcasted)

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
A=arr+arr.reshape(10,1)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [94]:
data=np.exp(np.random.randn(2,5))


In [95]:
print(data)

[[1.86521067 1.43076032 0.86157129 0.97106604 1.0412553 ]
 [0.99539779 0.83157454 1.19903573 0.51345479 1.1273181 ]]


In [96]:
means=np.mean(data,axis=0)
sd=np.std(data,axis=0)

In [97]:
print(means)
print(sd)

[1.43030423 1.13116743 1.03030351 0.74226041 1.0842867 ]
[0.43490644 0.29959289 0.16873222 0.22880563 0.0430314 ]


In [98]:
std_data=(data-means)/sd

In [99]:
new_means=np.mean(std_data,axis=0)
new_sd=np.std(std_data,axis=0)
print(new_means)
print(new_sd)

[ 2.22044605e-16 -2.22044605e-16  0.00000000e+00  2.22044605e-16
  0.00000000e+00]
[1. 1. 1. 1. 1.]
