### Name : Riddhick Dalal
### Reg No : 24-27-14
### Course : MTech Data Science
### Assignment 2

In [1]:
import numpy as np

### Question 1:

In [2]:
var1=np.arange(0,30+1,1)
print(var1)
print("Shape :"+str(var1.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape :(31,)


In [3]:
var2=var1[:-1].reshape(3,10)
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [4]:
var3=var1[:-1].reshape(3,5,2)
var3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [5]:
var2[1,0]=-1
var2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-1, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [6]:
print(var1)
print(var3)

[ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[-1 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [7]:
sum_over_second=np.sum(var3,axis=1)
print(sum_over_second)

[[ 20  25]
 [ 59  75]
 [120 125]]


In [8]:
sum_over_third=np.sum(var3,axis=2)
print(sum_over_third)

[[ 1  5  9 13 17]
 [10 25 29 33 37]
 [41 45 49 53 57]]


In [9]:
sum_over_first_second=np.sum(var3,axis=(0,2))
print(sum_over_first_second)

[ 52  75  87  99 111]


In [10]:
print(var2[1:2])
print(var2[0:,-1])
print(var2[:2,-2:])

[[-1 11 12 13 14 15 16 17 18 19]]
[ 9 19 29]
[[ 8  9]
 [18 19]]


#### Question 2 :


In [11]:
arr=np.arange(0,10,1)
arr_broadcasted=arr+1
print(arr_broadcasted)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
A=arr+arr.reshape(10,1)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [13]:
data=np.exp(np.random.randn(2,5))


In [14]:
print(data)

[[1.46302419 2.5870391  8.8505052  4.70811873 0.72261522]
 [0.94640007 1.26836814 1.11497842 7.37409162 0.24736618]]


In [15]:
means=np.mean(data,axis=0)
sd=np.std(data,axis=0)

In [16]:
print('Mean= '+str(means))
print('Standard Diviation= '+str(sd))

Mean= [1.20471213 1.92770362 4.98274181 6.04110518 0.4849907 ]
Standard Diviation= [0.25831206 0.65933548 3.86776339 1.33298645 0.23762452]


In [17]:
std_data=(data-means)/sd

In [18]:
new_means=np.mean(std_data,axis=0)
new_sd=np.std(std_data,axis=0)
print(new_means)
print(new_sd)

[-4.44089210e-16  0.00000000e+00 -1.66533454e-16 -3.88578059e-16
  1.11022302e-16]
[1. 1. 1. 1. 1.]


### Question 3 :

In [19]:
def vandermonde(N):
    vec=np.arange(N)+1
    vander=vec.reshape(N,1)
    vander=vander**np.arange(N)
    return vander
vander=vandermonde(12)
print(vander)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [20]:
x=np.ones(12)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
b=np.dot(vander,x)
b

array([1.20000000e+01, 4.09500000e+03, 2.65720000e+05, 5.59240500e+06,
       6.10351560e+07, 4.35356467e+08, 2.30688120e+09, 1.22713351e+09,
       9.43953692e+08, 3.73692871e+09, 3.10225064e+08, 3.10073456e+09])

In [22]:
inv_v=np.linalg.inv(vander)
res=np.dot(inv_v,b)
print(res)

[0.99559784 1.00491714 0.99946976 1.00000954 1.         0.99999917
 1.00000018 0.99999999 1.         1.         1.         1.        ]


#### The expected result was a vector having 12 ones, but in actual result some of the values are not exactly 1.

In [23]:
res2=np.linalg.solve(vander,b)
print(res2)


[1.0000114  0.99997033 1.00002961 0.99998507 1.00000423 0.9999993
 1.00000007 1.         1.         1.         1.         1.        ]


#### The result is more closer to the actual result.

### Github Link : <a href="https://github.com/Riddhick/Riddhick_Dalal_24-27-14">Github</a>

#### [https://github.com/Riddhick/Riddhick_Dalal_24-27-14]